#!/bin/bash
echo '14'
python simulation14.py
echo '13'
python simulation13.py
echo '12'
python simulation12.py
echo '11'
python simulation11.py
echo '10'
python simulation10.py
echo '9'
python simulation9.py
echo '8'
python simulation8.py
echo '7'
python simulation7.py
echo '6'
python simulation6.py
echo '5'
python simulation5.py
echo '4'
python simulation4.py
echo '3'
python simulation3.py
echo '2'
python simulation2.py
echo '1'
python simulation1.py
echo 'plot'
python plot.py
